version: 2.1

orbs:
  gem: goldstar/publish-gem@1.0.1

workflows:
  main:
    jobs:
      - gem/test:
          ruby-version: "2.6.6"
      - gem/build-and-deploy:
          context: packagecloud
          ruby-version: "2.6.6"
          requires:
            - gem/test
          filters:
            branches:
              only: master
          packagecloud-repo: goldstar/production
